Fix bugs of Slice/ReduceSum/TopK nodes and Graph's member function in corner cases
ThanatosShinji/onnx-tool pull request #15
Opened 2022-12-30 11:43 UTC by Treemann

Hi, I found some bugs and fixed them when processing a complicated case. The description of this pull requrest is: 

> Fix bugs of Slice/ReduceSum/TopK nodes in corner cases and optimize the member function (__find_shape_tensor__) of the Graph class

You could learn the details from the four commits history.

2022-12-30 17:41 UTC, ThanatosShinji commented
Hi, thanks for your contribution! Can you provide onnx models or pytorch(tf) scripts to test your fix?

2022-12-31 03:08 UTC, Treemann commented
Hi, subjected to the license, sorry that I could not send the model to you. 
But I could provide snapshots of the nodes related for your verification. I think the bug-fix is clear and easy to understand with these snapshots, you may test the code with your self-defined model if possible, or you could communicate with me if there is any question.
![slice](https://user-images.githubusercontent.com/8315383/210122989-b193602e-f459-4784-82c6-ed7694c23ec8.jpg)
![reduceSum](https://user-images.githubusercontent.com/8315383/210122996-d1c3839f-1800-40f7-9b60-4bf1021fb9cf.jpg)
![topk](https://user-images.githubusercontent.com/8315383/210123001-9340f0b4-b8fd-4032-b82f-e8463703740d.jpg)

2022-12-31 11:15 UTC, ThanatosShinji commented
Thanks again! I will use your fork repo to test all archived models. Then I will find a way to test these corner cases.

BTW, if it is convenient for you, you can use the ['extract subgraph'](https://github.com/ThanatosShinji/onnx-tool/blob/main/data/Subgraph.md) function to get the subgraph with these corner cases from your private models.  I think there is no secret in these subgraphs. Of course, it's all up to you.

2022-12-31 11:58 UTC, Treemann commented
Sorry for the inconvenience of uploading any subgraph to the internet~
I could explain the modification of each commit.
(1) Slice: like the snapshot of Slice node I provided, starts=[0,0,0,6], ends=[2147483647, 2147483647, 2147483647, 7], the order of both starts & ends are correspondent with the order of axes=[0,2,3,1]. So for axis=1, start=6, end=7; but the original code visit axes with the order of [0,1,2,3] instead of [0,2,3,1], then causes error.
(2) ReduceSum: like the snapshot of ReduceSum node I provided, if the node has two inputs, the second one is the list of axes. I notice that in node.py you have consider this situation, but in node_profiles.py you only consider the case of one input.
(3) TopK: like the snapshot of TopK node I provided, this node doesn't have the axis attribute, then self.axis=None. Since the input tensor has only one dimension, and the input shape of this node is (4000,), so TopK is conduced along axis=0 although    there is no axis attribute here.
(4) On the 4th commit [00d9a48](https://github.com/ThanatosShinji/onnx-tool/pull/15/commits/00d9a48ac23919e0bdc5b68894130ad766f35260), refer to the commit message and the part of my modification should be recovered to your original version according to our discussion on the issue.

2022-12-31 14:31 UTC, ThanatosShinji requested changes

2022-12-31 14:31 UTC, ThanatosShinji commented on onnx_tool/graph.py
> +                        # if node.op_type == 'Shape':
these codes need to be reverted.

2022-12-31 15:01 UTC, Treemann commented on onnx_tool/graph.py
> +                        # if node.op_type == 'Shape':
Done, please check the latest commit!

2022-12-31 16:06 UTC, ThanatosShinji approved these changes
All model tests passed.

2022-12-31 16:09 UTC, merged

2022-12-31 16:09 UTC, ThanatosShinji commented
Good work!