Fix Issues #36, #37 and more
ThanatosShinji/onnx-tool pull request #38
Opened 2023-07-28 08:37 UTC by aravinat21

Fix https://github.com/ThanatosShinji/onnx-tool/issues/36 and https://github.com/ThanatosShinji/onnx-tool/issues/37 and more

2023-07-28 09:39 UTC, ThanatosShinji requested changes
I think your pr is not ready for review. A lot of debug print here. Let me know when you are ready. Thanks for your contribution!

2023-07-28 09:39 UTC, ThanatosShinji commented on onnx_tool/node.py
> +        print('out', outtensors)
remove these debug codes

2023-07-28 09:39 UTC, ThanatosShinji commented on onnx_tool/node.py
> +                print('outvol', outvol)
remove these print

2023-07-28 11:14 UTC, aravinat21 commented
done plz check

2023-07-31 11:11 UTC, ThanatosShinji approved these changes

2023-07-31 11:11 UTC, merged