add op: HardSwishNode
ThanatosShinji/onnx-tool pull request #39
Opened 2023-07-31 06:46 UTC by YuRuiii

2023-07-31 11:16 UTC, ThanatosShinji requested changes

2023-07-31 11:16 UTC, ThanatosShinji commented on onnx_tool/node.py
> +        self.add_default_value('alpha',0.2)
The default value of alpha should be 1/6, please refer to https://onnx.ai/onnx/operators/onnx__HardSwish.html

2023-07-31 16:50 UTC, YuRuiii commented
Thanks for reminding me of that! I pushed my new code.

2023-08-01 10:53 UTC, ThanatosShinji approved these changes

2023-08-01 10:53 UTC, ThanatosShinji commented
Thanks for your contribution!

2023-08-01 10:54 UTC, merged