update scatterelements and scatter_nd_impl
ThanatosShinji/onnx-tool pull request #9
Opened 2022-11-15 02:10 UTC by MPolaris

update scatterelements and scatter_nd_impl codes from onnx repo.
scatterelements: https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/scatterelements.py#L2
scatter_nd_impl: https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/scatternd.py#L25

2022-11-15 09:19 UTC, ThanatosShinji commented
Hi, thanks for your contribution! There are two questions about your commit. Please answer them, then I can start to merge.

2022-11-17 00:56 UTC, MPolaris commented
Ok, What's your questions?

2022-11-17 10:39 UTC, ThanatosShinji commented
You can see there are two unsolved conversations in your PR. And my questions are within them. Looking forward to your answers.

2022-11-17 10:41 UTC, ThanatosShinji requested changes

2022-11-17 11:03 UTC, ThanatosShinji commented on onnx_tool/node_profilers.py
> +        if reduction == "add":
Format change from ONNX repo.

2022-11-17 11:05 UTC, ThanatosShinji approved these changes
I've confirmed these changes from ONNX repo.

2022-11-17 11:05 UTC, merged

2022-11-17 11:05 UTC, ThanatosShinji commented
Thanks for your contribution!